stages:
  - build

build:
  stage: build
  image: microsoft/dotnet:1.1.1-sdk
  script:
    - dotnet restore
    - dotnet build -c Release
    - cd test/MorleyDev.Reactive.Monad.UnitTests
    - dotnet test
